/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type LocaleText = {
  _type: "localeText";
  en: string;
  pl?: string;
};

export type LocaleString = {
  _type: "localeString";
  en: string;
  pl?: string;
};

export type Cv = {
  _id: string;
  _type: "cv";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  headline: LocaleString;
  location: LocaleString;
  summary: LocaleText;
  skills?: Array<{
    category?: LocaleString;
    items?: Array<string>;
    _type: "group";
    _key: string;
  }>;
  education?: Array<{
    qualification?: LocaleString;
    school?: string;
    period?: string;
    _type: "entry";
    _key: string;
  }>;
  languages?: Array<{
    name?: LocaleString;
    level?: LocaleString;
    _type: "entry";
    _key: string;
  }>;
};

export type Experience = {
  _id: string;
  _type: "experience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  role: LocaleString;
  org: string;
  dateLabel: LocaleString;
  current?: boolean;
  description: LocaleText;
  location?: string;
  bullets?: Array<
    {
      _key: string;
    } & LocaleString
  >;
  order: number;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: LocaleString;
  kind: LocaleString;
  client?: string;
  period: LocaleString;
  current?: boolean;
  description: LocaleText;
  outcome: LocaleText;
  stack: Array<string>;
  links?: Array<{
    label: string;
    url: string;
    _type: "link";
    _key: string;
  }>;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: LocaleString;
    _type: "shot";
    _key: string;
  }>;
  diagram?: "workflow-engine" | "data-blend" | "bff";
  onCv?: boolean;
  order: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | LocaleText
  | LocaleString
  | Cv
  | Experience
  | SanityImageAssetReference
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: ../sanity/queries.ts
// Variable: projectsQuery
// Query: *[_type == "project"] | order(order asc) {    _id,    title{ en, pl },    kind{ en, pl },    client,    period{ en, pl },    current,    description{ en, pl },    outcome{ en, pl },    stack,    links[]{ label, url },    diagram,    images[]{ alt{ en, pl }, asset->{ _id } }  }
export type ProjectsQueryResult = Array<{
  _id: string;
  title: {
    en: string;
    pl: string | null;
  };
  kind: {
    en: string;
    pl: string | null;
  };
  client: string | null;
  period: {
    en: string;
    pl: string | null;
  };
  current: boolean | null;
  description: {
    en: string;
    pl: string | null;
  };
  outcome: {
    en: string;
    pl: string | null;
  };
  stack: Array<string>;
  links: Array<{
    label: string;
    url: string;
  }> | null;
  diagram: "bff" | "data-blend" | "workflow-engine" | null;
  images: Array<{
    alt: {
      en: string;
      pl: string | null;
    };
    asset: {
      _id: string;
    } | null;
  }> | null;
}>;

// Source: ../sanity/queries.ts
// Variable: experienceQuery
// Query: *[_type == "experience"] | order(order asc) {    _id,    role{ en, pl },    org,    dateLabel{ en, pl },    current,    description{ en, pl }  }
export type ExperienceQueryResult = Array<{
  _id: string;
  role: {
    en: string;
    pl: string | null;
  };
  org: string;
  dateLabel: {
    en: string;
    pl: string | null;
  };
  current: boolean | null;
  description: {
    en: string;
    pl: string | null;
  };
}>;

// Source: ../sanity/queries.ts
// Variable: cvQuery
// Query: {    "profile": *[_type == "cv"][0]{      headline{ en, pl },      location{ en, pl },      summary{ en, pl },      skills[]{ category{ en, pl }, items },      education[]{ qualification{ en, pl }, school, period },      languages[]{ name{ en, pl }, level{ en, pl } }    },    "roles": *[_type == "experience"] | order(order asc) {      _id,      role{ en, pl },      org,      location,      current,      dateLabel{ en, pl },      description{ en, pl },      bullets[]{ en, pl }    },    "projects": *[_type == "project" && onCv == true] | order(order asc) {      _id,      title{ en, pl },      kind{ en, pl },      client,      period{ en, pl },      outcome{ en, pl },      stack,      links[]{ label, url }    }  }
export type CvQueryResult = {
  profile: {
    headline: {
      en: string;
      pl: string | null;
    };
    location: {
      en: string;
      pl: string | null;
    };
    summary: {
      en: string;
      pl: string | null;
    };
    skills: Array<{
      category: {
        en: string;
        pl: string | null;
      } | null;
      items: Array<string> | null;
    }> | null;
    education: Array<{
      qualification: {
        en: string;
        pl: string | null;
      } | null;
      school: string | null;
      period: string | null;
    }> | null;
    languages: Array<{
      name: {
        en: string;
        pl: string | null;
      } | null;
      level: {
        en: string;
        pl: string | null;
      } | null;
    }> | null;
  } | null;
  roles: Array<{
    _id: string;
    role: {
      en: string;
      pl: string | null;
    };
    org: string;
    location: string | null;
    current: boolean | null;
    dateLabel: {
      en: string;
      pl: string | null;
    };
    description: {
      en: string;
      pl: string | null;
    };
    bullets: Array<{
      en: string;
      pl: string | null;
    }> | null;
  }>;
  projects: Array<{
    _id: string;
    title: {
      en: string;
      pl: string | null;
    };
    kind: {
      en: string;
      pl: string | null;
    };
    client: string | null;
    period: {
      en: string;
      pl: string | null;
    };
    outcome: {
      en: string;
      pl: string | null;
    };
    stack: Array<string>;
    links: Array<{
      label: string;
      url: string;
    }> | null;
  }>;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "project"] | order(order asc) {\n    _id,\n    title{ en, pl },\n    kind{ en, pl },\n    client,\n    period{ en, pl },\n    current,\n    description{ en, pl },\n    outcome{ en, pl },\n    stack,\n    links[]{ label, url },\n    diagram,\n    images[]{ alt{ en, pl }, asset->{ _id } }\n  }\n': ProjectsQueryResult;
    '\n  *[_type == "experience"] | order(order asc) {\n    _id,\n    role{ en, pl },\n    org,\n    dateLabel{ en, pl },\n    current,\n    description{ en, pl }\n  }\n': ExperienceQueryResult;
    '\n  {\n    "profile": *[_type == "cv"][0]{\n      headline{ en, pl },\n      location{ en, pl },\n      summary{ en, pl },\n      skills[]{ category{ en, pl }, items },\n      education[]{ qualification{ en, pl }, school, period },\n      languages[]{ name{ en, pl }, level{ en, pl } }\n    },\n    "roles": *[_type == "experience"] | order(order asc) {\n      _id,\n      role{ en, pl },\n      org,\n      location,\n      current,\n      dateLabel{ en, pl },\n      description{ en, pl },\n      bullets[]{ en, pl }\n    },\n    "projects": *[_type == "project" && onCv == true] | order(order asc) {\n      _id,\n      title{ en, pl },\n      kind{ en, pl },\n      client,\n      period{ en, pl },\n      outcome{ en, pl },\n      stack,\n      links[]{ label, url }\n    }\n  }\n': CvQueryResult;
  }
}
