/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Experience = {
  _id: string;
  _type: "experience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  role?: string;
  org?: string;
  dateLabel?: string;
  current?: boolean;
  description?: string;
  order?: number;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  kind?: string;
  client?: string;
  period?: string;
  current?: boolean;
  description?: string;
  outcome?: string;
  stack?: Array<string>;
  links?: Array<{
    label?: string;
    url?: string;
    _type: "link";
    _key: string;
  }>;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  diagram?: "workflow-engine" | "data-blend" | "bff";
  order?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | Experience
  | SanityImageAssetReference
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: ../sanity/queries.ts
// Variable: projectsQuery
// Query: *[_type == "project"] | order(order asc) {    _id,    title,    kind,    client,    period,    current,    description,    outcome,    stack,    links[]{ label, url },    diagram,    image{      alt,      asset->{ url, metadata{ lqip, dimensions{ width, height } } }    }  }
export type ProjectsQueryResult = Array<{
  _id: string;
  title: string | null;
  kind: string | null;
  client: string | null;
  period: string | null;
  current: boolean | null;
  description: string | null;
  outcome: string | null;
  stack: Array<string> | null;
  links: Array<{
    label: string | null;
    url: string | null;
  }> | null;
  diagram: "bff" | "data-blend" | "workflow-engine" | null;
  image: {
    alt: string | null;
    asset: {
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
  } | null;
}>;

// Source: ../sanity/queries.ts
// Variable: experienceQuery
// Query: *[_type == "experience"] | order(order asc) {    _id,    role,    org,    dateLabel,    current,    description  }
export type ExperienceQueryResult = Array<{
  _id: string;
  role: string | null;
  org: string | null;
  dateLabel: string | null;
  current: boolean | null;
  description: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "project"] | order(order asc) {\n    _id,\n    title,\n    kind,\n    client,\n    period,\n    current,\n    description,\n    outcome,\n    stack,\n    links[]{ label, url },\n    diagram,\n    image{\n      alt,\n      asset->{ url, metadata{ lqip, dimensions{ width, height } } }\n    }\n  }\n': ProjectsQueryResult;
    '\n  *[_type == "experience"] | order(order asc) {\n    _id,\n    role,\n    org,\n    dateLabel,\n    current,\n    description\n  }\n': ExperienceQueryResult;
  }
}
